### ISSUE TITLE
txthinking/x 依赖问题

### ISSUE THREAD

**Issue by hahaliangchen** [xiaokangwang/VLite#5]
github.com/txthinking/x@v0.0.0-20200330144832-5ad2416896a9: invalid version: unknown revision 5ad2416896a9
作者你好， 我看txthinking那个项目一个月之前有大变动，之前的提交记录都没有了，只有一个main 分支了

**Comment by xiaokangwang** [comment]
已经通过把那个版本的库一起放进代码库搞定了
